# Part 0: Linear Algebra with NumPy

In [1]:
import numpy as np
from numpy import array, matrix

# Create a matrix

Let's go through a few ways to create the following two matrices. 


$$A = \left[ \begin{array}{cc}1 & 4 \\2 & 8 \end{array}\right] $$

$$x = \left[ \begin{array}{c}4 \\-1 \end{array}\right] $$




The main thing to figure out is how to get the matrix dimensions (or shape, using the NumPy term) right. 

##### Changing Shapes
The matrix shape can be altered by the following,

1. The structure of the array itself. A flat sequence creates a row matrix. In a sequence of sequences (list of lists for example), each sequence is a row. 


2. Transpose a matrix or an array with `.T` Note an array `np.array([1,2])` has shape `(2,)` and `np.array([[1,2]])` has shape `(1,2)`. Calling `.T` on the first does nothing, but `.T` does create a `(2,1)`-shaped array equivalent to `np.array([[1],[2]])`.


3. Use `.reshape()` method to change the dimension of an array or matrix. Applying `.reshape(2,2)` to a row matrix will fill the square matrix by row (left to right and then down to the next row). Observe `np.array([1,2]).reshape(1,2)` creates `np.array([[1,2]])`.

### Using `np.matrix`

First there is a class `np.matrix`. I like using this but the documentation says it's no longer recommended to use this class and it may be removed in the future, regular arrays should be used instead. Create a matrix directly with `np.matrix` or `np.asmatrix`.


In [2]:
# Working toward A
row_matrix1 = matrix( [1,4,2,8] )
row_matrix2 = matrix( array([1,4,2,8]) )
row_matrix3 = matrix( array([1,4,2,8]).T )
row_matrix4 = np.asmatrix( [1,4,2,8] )

column_matrix1 = matrix( array( [ [1],[4],[2],[8] ] ) )
column_matrix2 = matrix( array([1,4,2,8]) ).T
column_matrix3 = matrix( array([1,4,2,8]) ).reshape(4,1)

# So by default, arrays are turned into row 1xn row matrices. Use reshape to get A. 

A_from_row = row_matrix1.reshape(2,2)
A_from_column = column_matrix1.reshape(2,2)

In [3]:
row_matrix4

matrix([[1, 4, 2, 8]])

In [4]:
# Define x
x = matrix([4,-1]).reshape(2,1)
x

matrix([[ 4],
        [-1]])

### Using Regular Arrays

In [5]:
# These are all the same
A_array1 = array([[1,4],[2,8]])
A_array2 = array([[1,4,2,8]]).reshape(2,2)
A_array3 = array([1,4,2,8]).reshape(2,2)

In [6]:
x_array = array([4,-1]).reshape(2,1)

# Indexing Matrix Elements

Get the value at a particular index $i,j$ with `A[i,j]`.

Recall indexing starts at position zero in Python. 

In [7]:
print(A_from_row[0,0])
print(A_from_row[0,1])
print(A_from_row[1,0])
print(A_from_row[1,1])

1
4
2
8


In [8]:
try:
    print(A_from_row[2,0])
except IndexError:
    print("this fails because the row index of 2 is out of bounds")

this fails because the row index of 2 is out of bounds


##### Repeat for the arrays

In [9]:
print(A_array1[0,0])
print(A_array1[0,1])
print(A_array1[1,0])
print(A_array1[1,1])

1
4
2
8


# Multiply Matrices

With `np.matrix` objects, just use `*` to multiply. 

To take a matrix power, use the typical `**`. 

In [10]:
A_from_row * x

matrix([[0],
        [0]])

In [11]:
A_from_row**2

matrix([[ 9, 36],
        [18, 72]])

In [12]:
# Take an inverse with **-1
# or use `np.linalg.inv`

(x.T*x)**-1 * (x.T*x)

matrix([[1.]])

In [13]:
# these fail because it's a singular matrix
# np.linalg.inv(A_from_row)
# A_from_row**-1


new_matrix = A_from_row + np.matrix([2,0,0,0]).reshape(2,2)

# original matrix
print(new_matrix)

print() # just for spacing

# Inverse
print(new_matrix**-1)

print() # just for spacing


print((new_matrix * new_matrix**-1).round(3)) # apply rounding with .round()

[[3 4]
 [2 8]]

[[ 0.5    -0.25  ]
 [-0.125   0.1875]]

[[1. 0.]
 [0. 1.]]


### Matrix multiplication with arrays

`*` doesn't work with `np.array`. Use `np.matmul` instead. 

Similarly, `**` doesn't work to raise some matrix to a power. Use `np.linalg.inv` instead, or `np.linalg.matrix_power`.

This is why I don't like working with arrays. Typical operators work element-wise with arrays, not as matrix operations. 

In [14]:
A_array1 * x_array

array([[ 4, 16],
       [-2, -8]])

In [15]:
np.matmul(A_array1, x_array)

array([[0],
       [0]])

##### Powers and Inverses

In [16]:
# This is NOT AA. The operation is done element-wise.
A_array1**(2)

array([[ 1, 16],
       [ 4, 64]])

In [17]:
# make non-singular square matrix
new_array = A_array1 + np.array([2,0,0,0]).reshape(2,2)

In [18]:
# Original matrix
print(new_array)

print() # just for spacing

# Inverse, two ways
print(np.linalg.inv(new_array))
print(np.linalg.matrix_power(new_array,-1))

print()

print(np.matmul(new_array, np.linalg.inv(new_array)).round(3)) # apply rounding with .round()

[[3 4]
 [2 8]]

[[ 0.5    -0.25  ]
 [-0.125   0.1875]]
[[ 0.5    -0.25  ]
 [-0.125   0.1875]]

[[1. 0.]
 [0. 1.]]


# Special Matrices

Create a diagonal array with `np.diag`.

Find more array creation routines [here](https://numpy.org/doc/stable/reference/routines.array-creation.html).

In [19]:
# Create square diagonal matrix
diagonal = np.diag([1,2])
diagonal_matrix = matrix( diagonal )
print(diagonal_matrix)

[[1 0]
 [0 2]]


# More Linear Algebra Routines

[Documenation for Linear Algebra Routines in NumPy](https://numpy.org/doc/stable/reference/routines.linalg.html)

### Eigenvalues and Eigenvectors

What are the eigenvectors $v$ such that the matrix $A$ simple scales the matrix by $\lambda$?

$$ Av = \lambda v $$


In [20]:
A  = array([1,0,0,3]).reshape(2,2)

print(A)

np.linalg.eig(A)

[[1 0]
 [0 3]]


(array([1., 3.]),
 array([[1., 0.],
        [0., 1.]]))

In [21]:
np.linalg.eigvals(A)

array([1., 3.])

In [22]:
B = array([1,0,2,0]).reshape(2,2) #singular matrix

print(B)

np.linalg.eig(B)

[[1 0]
 [2 0]]


(array([0., 1.]),
 array([[0.        , 0.4472136 ],
        [1.        , 0.89442719]]))

### Determinants

The oriented area of the parallelogram formed by the matrix. [Wikipedia reference](https://en.wikipedia.org/wiki/Determinant)

In [23]:
print(np.linalg.det(A))

# np.linalg.det(A) == np.product(np.linalg.eigvals(A)) # True but off by rounding error
np.isclose(np.linalg.det(A), np.product(np.linalg.eigvals(A)))

3.0000000000000004


True

In [24]:
np.linalg.det(B)

0.0

### Singular Value Decomposition

Let $A$ be $2\times 1000$ with rank 2. $A$ has two positive singular values $\sigma_1$ and $\sigma_2$.

We need two sets of singular vectors, $u$'s and $v$'s. 

For a real $m\times n$ matrix, the $n$ right singular vectors $v_1, \dots, v_n$ are orthogonal in $\mathbb{R}^n$. 

The $m$ left singular vecotrs $u_1, \dots, u_m$ are perpendiuclar to each other in $\mathbb{R}^m$. 

Instead of $Ax = \lambda x$ like in the case of eigenvalues and eigenvectors for nice matrices, we have the following. 


$$Av_1 = \sigma_1 u_1, \cdots, Av_r = \sigma_r u_r$$
$$Av_{r+1} = 0, \cdots, Av_n = 0$$

The number $r$ is the rank of $A$–the number of independent columns or rows. 

There are $r$ positive singular values in descending order, $\sigma_1 \geq \sigma_2 \geq \dots \sigma_r \geq 0$.

The last $v$'s are n the nullspace of $A$ and the last $u$'s are in the nullspace of $A^T$.

In matrix form, 

$$ AV = U\Sigma,$$
where the columns of $V$ are $v_1, v_2, \dots, v_n$. The columns of $U$ are $u_1, u_2, \dots, u_m$. 

$\Sigma$ is a rectangular matrix with $\sigma_1, \dots, \sigma_r$ on the diagonal and then zeros in the remaining blocks. 

Remembe $A$ is $m\times n$, $V$ is $n\times n$, $U$ is $m\times m$. $\Sigma$ is $m\times n$.

&nbsp;


Finally, because $A$ is real, we have orthogonal $V$ and $U$. The SVD of $A$ is $$A = U\Sigma V^T.$$

In [25]:
C = np.arange(6).reshape(3,2)

In [26]:
u, s, vh = np.linalg.svd(C)
print(u)
print(s)
print(vh)

[[-0.10818576  0.90643763  0.40824829]
 [-0.48733624  0.30957507 -0.81649658]
 [-0.86648672 -0.28728749  0.40824829]]
[7.38648213 0.66323581]
[[-0.6011819  -0.79911221]
 [-0.79911221  0.6011819 ]]


In [27]:
A = (array([3,0,4,5])).reshape(2,2)

np.linalg.svd(A)

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]),
 array([6.70820393, 2.23606798]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Kronecker Product

$$ A\otimes B$$

$$A \otimes B= \left[ \begin{array}{cc}a_{11}B & a_{12}B \\ a_{21}B & a_{22}B \end{array}\right] $$

$$ A\otimes B \neq B \otimes A$$

In [28]:
A = np.identity(2)

In [29]:
B  = array([1,2,3,4]).reshape(2,2)

In [30]:
np.kron(A,B)

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [0., 0., 1., 2.],
       [0., 0., 3., 4.]])

In [31]:
np.kron(B,A)

array([[1., 0., 2., 0.],
       [0., 1., 0., 2.],
       [3., 0., 4., 0.],
       [0., 3., 0., 4.]])